sudo: false
language: node_js

node_js:
    - 4

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install -g grunt-cli bower
    - bower install
    - npm install

script:
    - npm run test-travis
